//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LazyVocabulary.Resources.Views.Dictionary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LazyVocabulary.Resources.Views.Dictionary.IndexResource", typeof(IndexResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить перевод.
        /// </summary>
        public static string AddTranslation {
            get {
                return ResourceManager.GetString("AddTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить выбранный словарь со всеми переводами? Восстановить данные будет.
        /// </summary>
        public static string AreYouSure1 {
            get {
                return ResourceManager.GetString("AreYouSure1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить все выбранные словари со всеми переводами? Восстановить данные будет.
        /// </summary>
        public static string AreYouSure2 {
            get {
                return ResourceManager.GetString("AreYouSure2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить словарь.
        /// </summary>
        public static string ButtonCreateDictionary {
            get {
                return ResourceManager.GetString("ButtonCreateDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить выбранные.
        /// </summary>
        public static string ButtonDeleteSelected {
            get {
                return ResourceManager.GetString("ButtonDeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снять выделение.
        /// </summary>
        public static string ButtonDeselectAll {
            get {
                return ResourceManager.GetString("ButtonDeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти словари.
        /// </summary>
        public static string ButtonSearch {
            get {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выделить все.
        /// </summary>
        public static string ButtonSelectAll {
            get {
                return ResourceManager.GetString("ButtonSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить поле.
        /// </summary>
        public static string ClearField {
            get {
                return ResourceManager.GetString("ClearField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите удаление.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создан:.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить словарь.
        /// </summary>
        public static string DeleteDictionary {
            get {
                return ResourceManager.GetString("DeleteDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать словарь.
        /// </summary>
        public static string EditDictionary {
            get {
                return ResourceManager.GetString("EditDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to невозможно..
        /// </summary>
        public static string Impossible {
            get {
                return ResourceManager.GetString("Impossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включая описания.
        /// </summary>
        public static string IncludingDescriptions {
            get {
                return ResourceManager.GetString("IncludingDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои словари.
        /// </summary>
        public static string PageName {
            get {
                return ResourceManager.GetString("PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество записей:.
        /// </summary>
        public static string RecordsCount {
            get {
                return ResourceManager.GetString("RecordsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите строку поиска.
        /// </summary>
        public static string SearchPattern {
            get {
                return ResourceManager.GetString("SearchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты поиска.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список переводов.
        /// </summary>
        public static string TranslationsList {
            get {
                return ResourceManager.GetString("TranslationsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновлён:.
        /// </summary>
        public static string UpdatedAt {
            get {
                return ResourceManager.GetString("UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не создали ни одного словаря..
        /// </summary>
        public static string YouDidntCreateAnyDictionary {
            get {
                return ResourceManager.GetString("YouDidntCreateAnyDictionary", resourceCulture);
            }
        }
    }
}
